version: '3'
services:
  server:
    image: redash/redash:${REDASH_IMAGE_TAG:-latest}
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - 127.0.0.1:5000:5000
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 2
    restart: always
  worker:
    image: redash/redash:${REDASH_IMAGE_TAG:-latest}
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    restart: always
  redis:
    image: redis:3.0-alpine
    restart: always
  postgres:
    image: postgres:9.5
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: playground
    volumes:
      - mysql:/var/lib/mysql
volumes:
  postgres:
    driver: local
  mysql:
    driver: local